---
title: "20220908.ex3"
author: "4621509 桐原巧"
date: "9/8/2022"
output: html_document
---

```{r}
source("../R/library.R")
source("../R/fixedvariable.R")
source("../R/selectdata.R")
source("../R/cal.q.length.R")
source("../R/item.leng.count.R")
#detectする関数
source("../R/longstring.R")
source("../R/IRV.R")
source("../R/mahad.R")
source("../R/psychsyn.R")
source("../R/ptc.R")

```

```{r}
#使うデータと長さ
use.colname=c("Q26","Q40","Q42","Q54","Q62","Q75")

#全てのuserIDと問題のデータを保存
alldata <- cal.naomit(use.colname) 
#q.length <- cal.q.length(use.colname)
```

```{r}
#user_idと問題データに分割する
user.id <- alldata %>% select(USER_ID)
qdata <- alldata %>% select(!USER_ID)

#削除した問題を考慮した問題の項目数ベクトル
item.leng <- item.leng.count(qdata)
q.length <- cal.q.length(use.colname,colnamedata=item.leng)

#検知方法の適用
long.result <- longstring(qdata,avg=F,split=T,q.length)
irv.result <- irv(qdata,na.rm = TRUE, split = T,q.length)
mahad.result <- mahad(qdata, plot = TRUE, flag = TRUE, confidence = 0.99, na.rm = TRUE)
psychsyn.result <- data.frame(psychsyn=psychsyn(qdata, critval=.60, anto=FALSE, diag=FALSE, resample_na=TRUE))
#psychant.result <- psychant(qdata, critval = -0.6, diag = FALSE)
ptc.result <- ptc(qdata,use.colname,split=FALSE) %>% rename("ptc"=out)

all.adhoc.result <- data.frame(long.result %>% select(!lsatotal),irv.result %>% select(!irvTotal),mahad.result %>% select(d_sq),psychsyn.result,ptc.result) %>% mutate(type = 1,.before = lsa1) %>% replace_na(replace = list(psychsyn=0,ptc=0))

```

### one-class svmの実装
```{r}
model <- ksvm(
  type~.,
  data = all.adhoc.result,
  type = 'one-svc',
  kpar = list(sigma=0.001),
  nu=0.02
)
```

```{r}
model
```

```{r}
pred <- predict(model, all.adhoc.result)
```

```{r}
str(pred)

table(pred)
```
```{r}
plot(all.adhoc.result$d_sq,all.adhoc.result$ptc,
     pch = 21,
     bg = c("red","green")[as.numeric(pred)+1]
     )
```
```{r}

```

